function out1 = func_G2(Lx2,Lx3,Lx4,Lxcm2,Lxcm3,Lxcm4,Lxcm5,Lxcm6,Lycm4,Lycm5,Lycm6,Lz6,Lzcm2,Lzcm3,Lzcm4,Lzcm5,Lzcm6,Q2,Q3,Q4,Q5,Q6,g2,g3,g4,g5,g6,m2,m3,m4,m5,m6)
%func_G2
%    OUT1 = func_G2(Lx2,Lx3,Lx4,Lxcm2,Lxcm3,Lxcm4,Lxcm5,Lxcm6,Lycm4,Lycm5,Lycm6,Lz6,Lzcm2,Lzcm3,Lzcm4,Lzcm5,Lzcm6,Q2,Q3,Q4,Q5,Q6,G2,G3,G4,G5,G6,M2,M3,M4,M5,M6)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    10-Sep-2025 01:57:00

t2 = cos(Q2);
t3 = cos(Q4);
t4 = cos(Q5);
t5 = cos(Q6);
t6 = sin(Q4);
t7 = sin(Q5);
t8 = sin(Q6);
t9 = Q2+Q3;
t10 = Q4+Q5;
t13 = -Q5;
t11 = cos(t9);
t12 = sin(t9);
t14 = Q4+t13;
t15 = Lx3.*g3.*m3.*t11;
t16 = Lx3.*g4.*m4.*t11;
t17 = Lx3.*g5.*m5.*t11;
t18 = Lx3.*g6.*m6.*t11;
t19 = Lxcm3.*g3.*m3.*t11;
t20 = Lzcm3.*g3.*m3.*t12;
t21 = Lzcm4.*g4.*m4.*t12;
t22 = Lx4.*g4.*m4.*t3.*t11;
t23 = Lx4.*g5.*m5.*t3.*t11;
t24 = Lx4.*g6.*m6.*t3.*t11;
t25 = Lxcm4.*g4.*m4.*t3.*t11;
t26 = Lycm4.*g4.*m4.*t6.*t11;
t27 = Lycm5.*g5.*m5.*t6.*t11;
t28 = Lz6.*g6.*m6.*t4.*t12;
t29 = Lzcm5.*g5.*m5.*t4.*t12;
t30 = Lzcm6.*g6.*m6.*t4.*t12;
t31 = Lxcm5.*g5.*m5.*t7.*t12;
t39 = Lycm6.*g6.*m6.*t5.*t6.*t11;
t40 = Lz6.*g6.*m6.*t3.*t7.*t11;
t41 = Lzcm6.*g6.*m6.*t3.*t7.*t11;
t42 = Lxcm6.*g6.*m6.*t6.*t8.*t11;
t43 = Lxcm6.*g6.*m6.*t5.*t7.*t12;
t44 = Lycm6.*g6.*m6.*t7.*t8.*t12;
t52 = Lxcm6.*g6.*m6.*t3.*t4.*t5.*t11;
t53 = Lycm6.*g6.*m6.*t3.*t4.*t8.*t11;
t32 = -t15;
t33 = -t16;
t34 = -t17;
t35 = -t18;
t36 = -t19;
t37 = -t20;
t38 = -t21;
t45 = -t22;
t46 = -t23;
t47 = -t24;
t48 = -t25;
t49 = -t28;
t50 = -t29;
t51 = -t30;
t54 = -t40;
t55 = -t41;
t56 = -t44;
t57 = -t52;
mt1 = [0.0;t26+t27+t31+t32+t33+t34+t35+t36+t37+t38+t39+t42+t43+t45+t46+t47+t48+t49+t50+t51+t53+t54+t55+t56+t57-Lzcm2.*g2.*m2.*sin(Q2)-Lx2.*g2.*m2.*t2-Lx2.*g3.*m3.*t2-Lx2.*g4.*m4.*t2-Lx2.*g5.*m5.*t2-Lx2.*g6.*m6.*t2-Lxcm2.*g2.*m2.*t2-(Lxcm5.*g5.*m5.*t11.*cos(t10))./2.0-(Lxcm5.*g5.*m5.*t11.*cos(t14))./2.0-(Lzcm5.*g5.*m5.*t11.*sin(t10))./2.0+(Lzcm5.*g5.*m5.*t11.*sin(t14))./2.0;t26+t27+t31+t32+t33+t34+t35+t36+t37+t38+t39+t42+t43+t45+t46+t47+t48+t49+t50+t51+t53+t54+t55+t56+t57-Lxcm5.*g5.*m5.*t3.*t4.*t11-Lzcm5.*g5.*m5.*t3.*t7.*t11];
mt2 = [t12.*(Lx4.*g4.*m4.*t6+Lx4.*g5.*m5.*t6+Lx4.*g6.*m6.*t6+Lxcm4.*g4.*m4.*t6+Lycm4.*g4.*m4.*t3+Lycm5.*g5.*m5.*t3+Lxcm5.*g5.*m5.*t4.*t6+Lxcm6.*g6.*m6.*t3.*t8+Lycm6.*g6.*m6.*t3.*t5+Lz6.*g6.*m6.*t6.*t7+Lzcm5.*g5.*m5.*t6.*t7+Lzcm6.*g6.*m6.*t6.*t7+Lxcm6.*g6.*m6.*t4.*t5.*t6-Lycm6.*g6.*m6.*t4.*t6.*t8);t3.*t31+t3.*t43+t3.*t49+t3.*t50+t3.*t51+t3.*t56-Lxcm5.*g5.*m5.*t4.*t11-Lz6.*g6.*m6.*t7.*t11-Lzcm5.*g5.*m5.*t7.*t11-Lzcm6.*g6.*m6.*t7.*t11-Lxcm6.*g6.*m6.*t4.*t5.*t11+Lycm6.*g6.*m6.*t4.*t8.*t11;g6.*m6.*(Lxcm6.*t5.*t6.*t12+Lxcm6.*t7.*t8.*t11+Lycm6.*t5.*t7.*t11-Lycm6.*t6.*t8.*t12+Lxcm6.*t3.*t4.*t8.*t12+Lycm6.*t3.*t4.*t5.*t12)];
out1 = [mt1;mt2];
end
