function out1 = func_G(Lx2,Lx3,Lxcm2,Lxcm3,Lxcm4,Lxcm5,Lxcm6,Lycm4,Lycm5,Lycm6,Lz4,Lz5,Lzcm2,Lzcm3,Lzcm4,Lzcm5,Lzcm6,Q2,Q3,Q4,Q5,Q6,g2,g3,g4,g5,g6,m2,m3,m4,m5,m6)
%func_G
%    OUT1 = func_G(Lx2,Lx3,Lxcm2,Lxcm3,Lxcm4,Lxcm5,Lxcm6,Lycm4,Lycm5,Lycm6,Lz4,Lz5,Lzcm2,Lzcm3,Lzcm4,Lzcm5,Lzcm6,Q2,Q3,Q4,Q5,Q6,G2,G3,G4,G5,G6,M2,M3,M4,M5,M6)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    30-Apr-2025 06:22:17

t2 = cos(Q2);
t3 = cos(Q3);
t4 = cos(Q4);
t5 = cos(Q5);
t6 = cos(Q6);
t7 = sin(Q2);
t8 = sin(Q3);
t9 = sin(Q4);
t10 = sin(Q5);
t11 = sin(Q6);
t12 = Q2+Q3;
t13 = cos(t12);
t14 = sin(t12);
t15 = t2.*t3;
t16 = t7.*t8;
t17 = -t16;
t18 = t15+t17;
t19 = Lx3.*t18;
et1 = -Lx2.*g3.*m3.*t2-Lx2.*g4.*m4.*t2-Lx2.*g5.*m5.*t2-Lx2.*g6.*m6.*t2-Lx3.*g4.*m4.*t15+Lx3.*g4.*m4.*t16-Lx3.*g5.*m5.*t15-Lx3.*g6.*m6.*t13+Lx3.*g5.*m5.*t16-Lxcm2.*g2.*m2.*t2-Lxcm3.*g3.*m3.*t13-Lz4.*g6.*m6.*t14-Lzcm2.*g2.*m2.*t7-Lzcm3.*g3.*m3.*t14-Lzcm4.*g4.*m4.*t14-Lxcm4.*g4.*m4.*t4.*t13+Lxcm5.*g5.*m5.*t10.*t14+Lycm4.*g4.*m4.*t9.*t13+Lycm5.*g5.*m5.*t9.*t13-Lz4.*g5.*m5.*t2.*t8-Lz4.*g5.*m5.*t3.*t7-Lz5.*g6.*m6.*t5.*t14-Lzcm5.*g5.*m5.*t5.*t14-Lzcm6.*g6.*m6.*t5.*t14-Lxcm5.*g5.*m5.*t4.*t5.*t13+Lxcm6.*g6.*m6.*t6.*t10.*t14+Lxcm6.*g6.*m6.*t9.*t11.*t13+Lycm6.*g6.*m6.*t6.*t9.*t13;
et2 = -Lycm6.*g6.*m6.*t10.*t11.*t14-Lz5.*g6.*m6.*t4.*t10.*t13-Lzcm5.*g5.*m5.*t4.*t10.*t13-Lzcm6.*g6.*m6.*t4.*t10.*t13-Lxcm6.*g6.*m6.*t4.*t5.*t6.*t13+Lycm6.*g6.*m6.*t4.*t5.*t11.*t13;
mt1 = [0.0;et1+et2;-g6.*m6.*(Lx3.*t13+Lz4.*t14+Lz5.*t5.*t14+Lzcm6.*t5.*t14-Lxcm6.*t6.*t10.*t14-Lxcm6.*t9.*t11.*t13-Lycm6.*t6.*t9.*t13+Lycm6.*t10.*t11.*t14+Lz5.*t4.*t10.*t13+Lzcm6.*t4.*t10.*t13+Lxcm6.*t4.*t5.*t6.*t13-Lycm6.*t4.*t5.*t11.*t13)-g4.*m4.*(t19+Lzcm4.*t14+Lxcm4.*t4.*t13-Lycm4.*t9.*t13)-g5.*m5.*(t19-Lxcm5.*(t10.*t14-t4.*t5.*t13)+Lzcm5.*(t5.*t14+t4.*t10.*t13)+Lz4.*(t2.*t8+t3.*t7)-Lycm5.*t9.*t13)-g3.*m3.*(Lxcm3.*t13+Lzcm3.*t14)];
mt2 = [t14.*(Lxcm4.*g4.*m4.*t9+Lycm4.*g4.*m4.*t4+Lycm5.*g5.*m5.*t4+Lxcm5.*g5.*m5.*t5.*t9+Lxcm6.*g6.*m6.*t4.*t11+Lycm6.*g6.*m6.*t4.*t6+Lz5.*g6.*m6.*t9.*t10+Lzcm5.*g5.*m5.*t9.*t10+Lzcm6.*g6.*m6.*t9.*t10+Lxcm6.*g6.*m6.*t5.*t6.*t9-Lycm6.*g6.*m6.*t5.*t9.*t11);-g5.*m5.*(Lxcm5.*(t5.*t13-t4.*t10.*t14)+Lzcm5.*(t10.*t13+t4.*t5.*t14))-g6.*m6.*(Lz5.*t10.*t13+Lzcm6.*t10.*t13+Lxcm6.*t5.*t6.*t13-Lycm6.*t5.*t11.*t13+Lz5.*t4.*t5.*t14+Lzcm6.*t4.*t5.*t14-Lxcm6.*t4.*t6.*t10.*t14+Lycm6.*t4.*t10.*t11.*t14);g6.*m6.*(Lxcm6.*t6.*t9.*t14+Lxcm6.*t10.*t11.*t13+Lycm6.*t6.*t10.*t13-Lycm6.*t9.*t11.*t14+Lxcm6.*t4.*t5.*t11.*t14+Lycm6.*t4.*t5.*t6.*t14)];
out1 = [mt1;mt2];
end
